version: '2'

services:
  # frontend:
  #     build : 
  #       context : . 
  #       dockerfile : ./front/Dockerfile
  #     environment:
  #       CHOKIDAR_USEPOLLING: "true"
  #     ports :
  #       - "3000:3000"
  #     volumes:
  #       - './front/:/app'
  #       - '/app/node_modules'
  #     # command : npm start
  #     extra_hosts:
  #     - "host.docker.internal:host-gateway"
      
  web :
    depends_on:
      - db 
    build : "./full_stack"
    ports : 
      - "8000:8000"
    volumes : 
      - ./full_stack:/src
    # python3 manage.py migrate && 
    command: bash -c "python3 manage.py makemigrations & python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:8000"
  
  db:
    image: postgres:13
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
       - ./full_stack/postgres:/var/lib/postgresql/data
